name: TM4C compile check (syntax-only)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ARM GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Compile all C files to .o (no linking)
        shell: bash
        run: |
          set -e
          mkdir -p build
          # Compiler flags for TM4C123 (Cortex-M4F)
          CFLAGS="-mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard \
                  -std=c11 -O2 -g3 -ffunction-sections -fdata-sections \
                  -Wall -Wextra -Wno-implicit-function-declaration \
                  -DPART_TM4C123GH6PM -I."
          # Find all .c files except typical CCS output folders
          mapfile -t SRC < <(git ls-files '*.c' | grep -Ev '(^|/)(Debug|Release|.metadata|targetConfigs)/')
          if [ ${#SRC[@]} -eq 0 ]; then
            echo "No .c files found"
            exit 1
          fi
          # Compile each file to a parallel build/ path
          for f in "${SRC[@]}"; do
            of="build/${f%.c}.o"
            mkdir -p "$(dirname "$of")"
            echo "Compiling $f"
            arm-none-eabi-gcc $CFLAGS -c "$f" -o "$of"
          done

      - name: Upload .o artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tm4c-objects
          path: build/**/*.o
